const OLX_CONFIGS = {
  pl: {
    countryCode: 'pl',
    baseUrl: 'https://www.olx.pl',
    cardSelector: 'div[data-cy="l-card"]',
    linkSelectors: ['a[href*="/d/oferta/"]', 'a[href]'],
    titleSelectors: ['[data-testid="ad-card-title"] h4', 'h4'],
    imageSelector: 'img',
    imageAttributes: ['src', 'data-src'],
    priceSelectors: ['[data-testid="ad-price"]'],
    pricePatternSource: '([\\d\\s.,]+\\s*zł)',
    pricePatternFlags: 'i',
    priceReturnTextWhenNoMatch: false,
    shippingContains: 'Pakietem Ochronnym',
    shippingLabel: 'Pakiet Ochronny',
  },
  pt: {
    countryCode: 'pt',
    baseUrl: 'https://www.olx.pt',
    cardSelector: 'div[data-cy="l-card"], div[data-testid="l-card"]',
    linkSelectors: ['a[href*="/d/anuncio/"]', 'a[href]'],
    titleSelectors: ['[data-testid="ad-card-title"] h4', 'h4'],
    imageSelector: 'img',
    imageAttributes: ['srcset', 'data-srcset', 'src', 'data-src'],
    priceSelectors: ['[data-testid="ad-price"]'],
    pricePatternSource: '([\\d\\s.,]+\\s*€)',
    pricePatternFlags: 'i',
    priceReturnTextWhenNoMatch: true,
    shippingSelectors: ['[data-testid="location-date"]'],
  },
  ro: {
    countryCode: 'ro',
    baseUrl: 'https://www.olx.ro',
    cardSelector: 'div[data-cy="l-card"], div[data-testid="l-card"]',
    linkSelectors: ['a[href*="/d/oferta/"]', 'a[href]'],
    titleSelectors: ['[data-testid="ad-card-title"] h4', 'h4'],
    imageSelector: 'img',
    imageAttributes: ['srcset', 'data-srcset', 'src', 'data-src'],
    priceSelectors: ['[data-testid="ad-price"]'],
    pricePatternSource: '([\\d\\s.,]+\\s*lei)',
    pricePatternFlags: 'i',
    priceReturnTextWhenNoMatch: true,
    shippingSelectors: ['[data-testid="location-date"]'],
  },
  ua: {
    countryCode: 'ua',
    baseUrl: 'https://www.olx.ua',
    cardSelector: 'div[data-cy="l-card"], div[data-testid="l-card"]',
    linkSelectors: ['a[href*="/d/uk/obyavlenie/"]', 'a[href*="/d/obyavlenie/"]', 'a[href]'],
    titleSelectors: ['[data-testid="ad-card-title"] h4', 'h4'],
    imageSelector: 'img',
    imageAttributes: ['srcset', 'data-srcset', 'src', 'data-src'],
    priceSelectors: ['[data-testid="ad-price"]'],
    pricePatternSource: '([\\d\\s.,]+\\s*(?:грн\\.?|₴))',
    pricePatternFlags: 'i',
    priceReturnTextWhenNoMatch: true,
    shippingSelectors: ['[data-testid="location-date"]'],
  },
  bg: {
    countryCode: 'bg',
    baseUrl: 'https://www.olx.bg',
    cardSelector: 'div[data-cy="l-card"], div[data-testid="l-card"]',
    linkSelectors: ['a[href*="/d/ad/"]', 'a[href]'],
    titleSelectors: ['[data-testid="ad-card-title"] h4', 'h4'],
    imageSelector: 'img',
    imageAttributes: ['srcset', 'data-srcset', 'src', 'data-src'],
    priceSelectors: ['[data-testid="ad-price"]'],
    pricePatternSource: '([\\d\\s.,]+\\s*лв\\.?)(?:\\s*\\/\\s*[\\d\\s.,]+\\s*€)?',
    pricePatternFlags: 'i',
    priceReturnTextWhenNoMatch: true,
    shippingSelectors: ['[data-testid="location-date"]'],
  },
  kz: {
    countryCode: 'kz',
    baseUrl: 'https://www.olx.kz',
    cardSelector: 'div[data-cy="l-card"], div[data-testid="l-card"]',
    linkSelectors: ['a[href*="/d/obyavlenie/"]', 'a[href]'],
    titleSelectors: ['[data-testid="ad-card-title"] h4', 'h4'],
    imageSelector: 'img',
    imageAttributes: ['srcset', 'data-srcset', 'src', 'data-src'],
    priceSelectors: ['[data-testid="ad-price"]'],
    pricePatternSource: '([\\d\\s.,]+\\s*(?:тг\\.?|₸))',
    pricePatternFlags: 'i',
    priceReturnTextWhenNoMatch: true,
    shippingSelectors: ['[data-testid="location-date"]'],
  },
  ba: {
    countryCode: 'ba',
    baseUrl: 'https://olx.ba',
    cardSelector: 'div.cardd, div[class*="cardd"]',
    linkSelectors: ['a[href*="/artikal/"]', 'a[href]'],
    titleSelectors: ['h1.main-heading', 'h1', '[class*="heading"]'],
    imageSelector: '.case-slider__image img, img',
    imageAttributes: ['src', 'data-src'],
    priceSelectors: ['.price-wrap .smaller', '[class*="price"] .smaller', '[class*="price"]'],
    pricePatternSource: '([\\d\\s.,]+\\s*KM)',
    pricePatternFlags: 'i',
    priceReturnTextWhenNoMatch: true,
    shippingSelectors: ['.price-wrap .text-xs', '.text-xs'],
  },
};

export function getOlxConfig(country) {
  return OLX_CONFIGS[country] || OLX_CONFIGS.pl;
}